version: '3.3'

services: 
  db:
    image: mysql:latest
    container_name: mysql
    ports: 
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./data/redis:/data
    ports: 
      - "6380:6380"
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/nginx-proxy/certs:/etc/nginx/certs
      - ./configs/nginx-proxy/dhparam:/etc/nginx/dhparam
      - /var/run/docker.sock:/tmp/docker.sock:ro
  web:
    build: ./build/web
    image: php7web:latest
    hostname: web_dev
    container_name: web
    volumes:
      - ./src/web:/var/www
      - ./configs/web/sites-enabled:/etc/apache2/sites-enabled
      - ./logs/web/apache2:/var/log/apache2
    depends_on:
      - db
      - redis
    environment:
      - VIRTUAL_HOST=host1.local
  web2: 
    build: ./build/web
    image: php7web:latest
    hostname: web_dev2
    container_name: web2
    volumes:
      - ./src/web2:/var/www
      - ./configs/web2/sites-enabled:/etc/apache2/sites-enabled
      - ./logs/web2/apache2:/var/log/apache2
    depends_on:
      - db
      - redis
    environment:
      - VIRTUAL_HOST=host2.local
